# Generated by Django 4.2 on 2024-01-06 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_emailverificationcode_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
