# Generated by Django 3.2.4 on 2021-06-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['auc_end_time']},
        ),
    ]
