# Generated by Django 4.2 on 2024-01-22 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_notificatin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificatin',
            new_name='Notification',
        ),
    ]
