# Generated by Django 4.2 on 2024-01-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_notification_type_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='bid',
        ),
        migrations.AddField(
            model_name='notification',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
