# Generated by Django 4.2 on 2024-01-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_notification_bid_notification_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.auction'),
        ),
    ]
